config/routes.rb
Rails.application.routes.draw do
  devise_for :users
resources:movies
resources:reviews
root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
belongs_to :user
belongs_to :category
has_many :reviews
has_attached_file :movie_img, styles: { movie_index: "250x350>", image_show: "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :movie_img, content_type: /\Aimage\/.*\z/
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :movie
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :movies
	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
before_action :find_movie, only: [:show, :edit, :update, :destroy]

def index
	if params[:category].blank?
       @movies = Movie.all.order("created_at DESC")
	else
		@category_id = Category.find_by(mane: params[:category]).id
		@movies = Movie.where(:category_id => @category_id).order("created_at DESC")
	end

end

def show
 	
end
def new 
	@movie = current_user.movies.build
	@categories =Category.all.map{ |c| [c.mane, c.id]}	
end
def create
	@movie = current_user.movies.build(movie_params)
	@movie.category_id = params[:category_id]  
	if @movie.save
		redirect_to root_path
	else
		render 'new'
	end
end

def edit
 	@categories =Category.all.map{ |c| [c.mane, c.id]}	
   
end
def update
	@movie.category_id = params[:category_id]  
 if @movie.update(movie_params)
    redirect_to movie_path(@movie)
   else
     render 'edit'
  end  
end
def destroy
  @movie.destroy
  redirect_to root_path  
end

private
def movie_params
	params.require(:movie).permit(:movie_img, :title, :description, :author, :category_id )
end
def find_movie
@movie = Movie.find(params[:id])
end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :find_movie
def new
	@review =Review.new
end
def create
	@review = Review.new(review_params)	
	@review.movie_id = @movie.id
	@review.user_id = current_user.id
	if @review.save
		redirect_to_movie_path(@movie)
		
	else
		render 'new'
	end
end
private
 
 def review_params
 	params.require(:review).permit(:rating, :comment)
 end
 def find_movie
 	@movie = Movie.find(params[:id])
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReviews</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Movie Details", root_path, class: "navbar-brand" %>
        </div>
        <ul class= "nav navbar-nav">
        <li> <%= link_to "Sign up", new_user_registration_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>

          <% else %>
          <li> <%= link_to "Log In", new_user_session_path %></li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">

  
            <ul class="nav navbar-nav">
              <% Category.all.each do |category| %>
              <li class="<%= 'active' if params[:category] == category.mane %>">
                <%= link_to category.mane,movies_path(category: category.mane), class: "link" %>
              </li>
              <% end %>
                
              
            </ul>
           

        <% if user_signed_in? %>
          <li><%= link_to "Add Movie",new_movie_path %></li>
        <% end %>
        </ul>
      </div>

    </nav>
  	<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       <div class ="container">

         <%= yield %>
  </container>
  </body>
</html>

app/views/movies/_form.html.erb
<div class="container">
<%= simple_form_for @movie, :html => { :multipart =>true} do |f| %>
<%= select_tag(:category_id, options_for_select(@categories))%>
<%= f.input :title, label: "Movie Title" %>
<%= f.input :description %>
<%= f.input :author %>
<%= f.button :submit %>
<% end %>
</div>

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>
<%= simple_form_for @movie, :html => { :multipart =>true} do |f| %>
<%= f.select :category_id, @categories %>
<%= f.input :title, label: "Movie Title" %>
<%= f.input :description %>
<%= f.input :author %>
<%= f.button :submit %>
<% end %>

app/views/movies/index.html.erb

<h2>All Aviliable Movies</h2>
<h1 class ="current-category"><%= params[:category] %></h1>
<% if @movies.count ==0 %>
<h1> There are currently no movies in this category</h1>

   <% else %>
   <div class="row">

    <% @movies.each do |movie| %>
    <div class ="col-md-4">
    	<div class="movie">
    <h3><%= link_to movie.title, movie_path(movie), class:"anchor" %></h3>
</div>
</div>

 <% end %>
</div>

<% end %>


app/views/movies/new.html.erb
<h2>Add Movie</h2>

<%= render 'form' %>

app/views/movies/show.html.erb
<div class="row">
	<div class="col-md-3">
		<%=image_tag("movie.jpg", alt: "Example Image",  :size => "250x350")%>
	</div>

	
	
<div class="col-md-8">
	<h2><%= @movie.title      %></h2>
	<h3>Director:<%= @movie.author      %></h3>
	
	<p>Details:<%= @movie.description      %></p>
	</div>
</div>

<%= link_to "Back", root_path %>

<% if user_signed_in?   %>

	<% if @movie.user_id ==current_user.id %>

	<%= link_to "Edit", edit_movie_path(@movie) %>
	<%= link_to "Delete", movie_path(@movie), method: :delete, data: {confirm: "Are you Sure to delete"} %>
	<% end %>
<% end %>

app/views/reviews/_form.html.erb
<%= simple_form_for[@movie,@movie.reviews.build] do |f| %>
<%= f.input :rating %>
<%= f.input :comment %>
<%= f.button :submit %

<% end %>

app/views/reviews/new.html.erb
<h1>New Review</h1>
<% render 'form' %>